#连接数据库
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncodeing=utf8&serverTimezone=UTC&useSSL=false
      username: root
      password: lx@lx19870613
      initial-size: 3
      min-idle: 3
      max-active: 30
      max-wait: 15000
      validation-query: SELECT 'x'
      #监控配置
      stat-view-servlet:
        login-username: system
        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
        enabled: true
#配置thymeleaf
  thymeleaf:
    cache: false
    enabled: true
#mybatis的配置
#mybatis:
#mybatis-plus的配置
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  configration:
    global-config:
      db-config:
        id-type: auto  #配置全局的id自动增长
